### PR TITLE
RenameLocalVariable :)

### PR DESCRIPTION
**Pull request by nrocy**
Hey!

Does what it says on the tin, I've merged upstream already so should be an easy merge for you :)

Also there's a technique in there for backing up @registers to avoid clobbering them, according to #vim on FreeNode, you can't yank into local variables. :(
- Paul

### CODE REVIEW

**Comment by ecomba** [comment]
Ooops!

Error detected while processing function RenameLocalVariable:
line   29:
E486: Pattern not found: <\zssomething>\ze[^(]

**Comment by nrocy** [comment]
Oops indeed!

Was it a variable in a method, or in global scope?  Got a snippet/steps to reproduce please?

**Comment by ecomba** [comment]
I had this method here: 

 26   def arg
 27     something = 3+4
 28     bla + somethig
 29     return something
 30   end

Selected in visual mode the first occurrence of "something" and tried to run the script <leader>rrlv

**Comment by nrocy** [comment]
Hey Enrique,

Have added a dependency check into the plugin for now, it's actually fairly hard to match the corresponding end token.  As such, figure better safe than sorry :)   Gives an error message stating requirement, and where to download plugin from.
- Paul

**Comment by ecomba** [comment]
Well done!

**Pull request merged**
